### PR TITLE
3 efa

### PR DESCRIPTION
**Pull request by laywang142**
Hello. Added some unit tests. Would appreciate some feedback. Thanks.

### CODE REVIEW

**Comment by wangh107** [comment]
@laywang142 `master` branch is reserved for pulling changes from origin. 
all unit tests will be merged to `devel`.  I've changed the base branch to `devel` in this pull request.

**Comment by wangh107** [comment]
close #3

**Comment by wangh107** [comment]
@laywang142 
Is it still work in progress or ready to review?

**Comment by Dura-Europos** [comment]
@laywang142 Three "Working case using sample cov" tests throw this error
```
── Error (Line 5): Working case using sample cov - 1 ───────────────────────────
Error in `efa(sample.cov = data, sample.nobs = 2)`: lavaan ERROR: when nvar = 0 the maximum number of factors is 0
Backtrace:
 1. lavaan::efa(sample.cov = data, sample.nobs = 2)

Error in reporter$stop_if_needed() : Test failed
```

**Review by Dura-Europos — CHANGES_REQUESTED** [review]
All three "Working case using sample cov" Throw this error

```
── Error (Line 5): Working case using sample cov - 1 ───────────────────────────
Error in `efa(sample.cov = data, sample.nobs = 2)`: lavaan ERROR: when nvar = 0 the maximum number of factors is 0
Backtrace:
 1. lavaan::efa(sample.cov = data, sample.nobs = 2)

Error in reporter$stop_if_needed() : Test failed
```

**Comment by laywang142** [comment]
@Dura-Europos The tests all seemed to pass when I ran them locally

**Review by Dura-Europos — APPROVED** [review]

**Comment by Dura-Europos** [comment]
Tests passed

Screenshot 2024-02-02 144211

**Pull request merged**
