### PR TITLE
Fix test lav test wald

### PR DESCRIPTION
**Pull request by Dura-Europos**

### CODE REVIEW

**Comment by Dura-Europos** [comment]
@laywang142 I fixed the first test by removing `b3 == 1`. I am not familiar with this function so please check whether this change is OK.

**Review by laywang142 — COMMENTED** [review]
The thing with the `b3 == 1` condition is that it should trigger [this code](https://github.com/wangh107/lavaan/blob/master/R/lav_test_Wald.R#L20-L25), which is theoretically supposed to remove the constraint from the object's parameter table, but I guess they changed the structure of the parameter table recently so it doesn't quite do that anymore.

**Comment by Dura-Europos** [comment]
- [ ] Raise the issue on https://github.com/wangh107/lavaan/blob/master/R/lav_test_Wald.R#L20-L25

**Comment by Dura-Europos** [comment]
Bug fixed by the author. No need to fix tests here

**Pull request closed without merging**
